package vn.edu.fpt.doghandbook.backend.entity.enums;

public enum NotificationType {
    CONTENT_SUBMITTED,
    CONTENT_APPROVED,
    CONTENT_REJECTED,
    CONTENT_REVISION_REQUESTED,
    CONTENT_PUBLISHED,
    CONTENT_UNPUBLISHED,
    SUGGESTION_SUBMITTED,
    SUGGESTION_REVIEWED,

    ASSIGNMENT_CREATED,

    HEALTH_SESSION_CREATED,
    HEALTH_SESSION_RESOLVED,

    FOLLOWUP_DUE,

    WEIGHT_ABNORMAL,

    SYNC_CONFLICT,

    // Escalation (Trainer + Admin)
    WEIGHT_ABNORMAL_CRITICAL,
    HEALTH_SESSION_CRITICAL,
    FOLLOWUP_OVERDUE_ESCALATION,
    REPEATED_SYNC_FAILURE,
    ABNORMAL_REASSIGNMENT
}
